FROM python:3.14-slim
RUN apt-get update
RUN apt-get install -y build-essential
COPY . /app
WORKDIR /app
RUN pip install -r app/requirements.txt
RUN chmod -R 755 /app
RUN apt-get purge -y build-essential && apt-get autoremove -y
RUN rm -rf /var/lib/apt/lists/*
CMD ["python", "app/app.py"]
